package com.igo.kenavgraph_copy2

const val ARG_COLOR = "ARG_COLOR"
const val ARG_COLOR_NAME = "ARG_COLOR_NAME"
const val PREVIOUS_KEY = "PREVIOUS_KEY"
const val PREVIOUS_KEY_PROCESSED = "PREVIOUS_KEY_PROCESSED"
const val REQUEST_CODE = "REQUEST_CODE"
const val REQUEST_CODE_EXTRA = "REQUEST_CODE_EXTRA"

